title: "Back-End Engineering Curriculum - Turing School of Software and Design"
description: "Open source curriulum for the Turing School of Software and Design's back end engineering program."
url: "http://backend.turing.io/"

baseurl: ''
permalink: /:title

markdown: redcarpet
kramdown:
  input: GFM
  syntax_highlighter: rouge

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "with_toc_data", "fenced_code_blocks"]

exclude: [
  'Gemfile',
  'Gemfile.lock',
  'README.md',
  'LICENSE',
  'CNAME'
]

defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"

assets:
  root_url: '/assets'

images:
  root_url: '/assets/images'

gems:
  - jemoji
